### ISSUE TITLE
No packages found

### ISSUE THREAD

**Issue by demueller** [brdude/pulp_centos_errata_import#10]
Hello guys,
after trying out your skript but im getting a lot of erros:
and that i think for every package.
I follower the steps:
synced all repos
wget newest repo.xml
launched the skript
and synced all repos again but no effect.

```
Successfully logged in. Session certificate will expire at May 24 16:21:49 2016
GMT.
INFO: Login successful
INFO: Loading errata XML
INFO: Getting server inventory
TICE: Skipping errata CEBA-2005:842 (Important CentOS shadow-utils - bugfix update) -- No packages found
NOTICE: Skipping errata CEBA-2006:0613 (Important CentOS freetype - bugfix update) -- No packages found
NOTICE: Skipping errata CEBA-2007:0080 (CentOS gcc - bugfix update) -- No packages found
NOTICE: Skipping errata CEBA-2007:0101 (CentOS gcc4 - bugfix update) -- No packages found
NOTICE: Skipping errata CEBA-2007:0159 (CentOS rgmanager Update) -- No packages found
NOTICE: Skipping errata CEBA-2007:0160 (CentOS gfs-utils Update) -- No packages found
...
...
...
Session certificate successfully removed.

```

CentOS 7
Katello 2.4
I would appreciate any help.
Greets

**Comment by rdrgmnzs** [comment]
This is probably the same issue as the bug described in #7 the branch https://github.com/brdude/pulp_centos_errata_import/tree/0.4.0 should fix this, but I haven't had time to fully test it. Any help would be appreciated.

**Comment by demueller** [comment]
Thank you for your reply.
I changed to 0.4.0 branch and started the skript egain but no change for me, same errors.

**Comment by rdrgmnzs** [comment]
Huh, then it may be another problem I've hit in the past. Try passing the repos you want to load the errata for with the --include-repo flag.

**Comment by rpere** [comment]
I've run into this same issue lately and yes this flag is needed - btw thanks for doing this, this is a great project!

**Comment by rdrgmnzs** [comment]
@demueller, @rpere I believe this stems from the fact that every time a new "Content View" is published a new "repo" is created by Katello. Unfortunately this script is not smart enough to figure out which ones are the original repo (where you want to insert the errata) and which are Katello created.

I'll hopefully have some time to do some testing of the new version, this coming weekends and will try to add some more documentation to it.

**Comment by rpere** [comment]
Great thank you for your efforts, btw I have noticed this against pulp-server (version 2.8) i'm not using Katello.
I think that [this line of code](https://github.com/brdude/pulp_centos_errata_import/blob/master/errata_import.pl#L122) will no longer work with `v2.8` (more specifically the `-s` option) :

**Comment by rdrgmnzs** [comment]
@rpere looks like I asked you to test code in 0.4.0 which I had worked on a while back but never tested and committed sorry about that. 

As for the issue you are experiencing it's most likely due to the pulp-admin login no longer being supported (I just tested and the -s flag still works on 2.8 on the https://github.com/Katello/katello-deploy vagrant with Katello 3.0)

I'm finalizing some testing and will publish the 0.4.0 branch to master. Sorry for any inconveniences this may have caused.

P.S. Feel free to re-open this if the issue is not solved with 0.4.0 now that I finally comited the code.

**Comment by demueller** [comment]
Hi,
im still have the same Problem with "--include-repo". I have a "Base" Repo. 
./errata_import.pl --debug --errata=errata.latest.xml --user=admin --password=**\* --include-repo=Base.
`DEBUG: Called as ./errata_import.pl --debug --errata=errata.latest.xml --user=admin --password=**\* --include-repo=Base
DEBUG: Version is 20150616
Successfully logged in. Session certificate will expire at Jun 16 13:08:04 2016
GMT.

INFO: Login successful
INFO: Loading errata XML
...
DEBUG: Package: xen-hypervisor-4.2.5-38.el6.centos.alt.x86_64.rpm not found
DEBUG: Package: xen-libs-4.2.5-38.el6.centos.alt.x86_64.rpm not found
DEBUG: Package: xen-licenses-4.2.5-38.el6.centos.alt.x86_64.rpm not found
DEBUG: Package: xen-ocaml-4.2.5-38.el6.centos.alt.x86_64.rpm not found
DEBUG: Package: xen-ocaml-devel-4.2.5-38.el6.centos.alt.x86_64.rpm not found
DEBUG: Package: xen-runtime-4.2.5-38.el6.centos.alt.x86_64.rpm not found
NOTICE: Skipping errata CESA-2105:X001 (Important xen kernel libvirt python-virtinst e1000e (Xen4CentOS Only) Security Update) -- No packages found
DEBUG: Skipping meta
DEBUG: Logging out.
Session certificate successfully removed.
`

**Comment by rdrgmnzs** [comment]
@demueller looks like you are using a old version of this script, which uses a cert based Pulp login that pulp no longer supports. I can tell because of this line:
DEBUG: Logging out.

There are 2 ways to get around this one is to modify your configs like mentioned on this bug report http://projects.theforeman.org/issues/12841, the other is to update your code to the newest one on master. The newest code of this script no longer uses cert based auth.

**Comment by demueller** [comment]
@brdude i updated the script to the latest version, still no luck:
DEBUG: Version is 20150616
INFO: Loading errata XML
DEBUG: XML loaded successfully
INFO: Getting server inventory
DEBUG: Using repo list from command line options: Base
DEBUG: Getting errata from Base
DEBUG: Processing CEBA-2005:169
DEBUG: Package: up2date-4.4.5.6-2.centos4.i386.rpm not found
DEBUG: Package: up2date-4.4.5.6-2.centos4.src.rpm not found
DEBUG: Package: up2date-4.4.5.6-2.centos4.x86_64.rpm not found
DEBUG: Package: up2date-gnome-4.4.5.6-2.centos4.i386.rpm not found
...
...
...
DEBUG: Package: xen-ocaml-devel-4.2.5-38.el6.centos.alt.x86_64.rpm not found
DEBUG: Package: xen-runtime-4.2.5-38.el6.centos.alt.x86_64.rpm not found
NOTICE: Skipping errata CESA-2105:X001 (Important xen kernel libvirt python-virtinst e1000e (Xen4CentOS Only) Security Update) -- No packages found
DEBUG: Skipping meta
